### ISSUE TITLE
Update yargs

### ISSUE THREAD

**Issue by wojtekmaj** [dbhowell/pino-cloudwatch#21]
Hi,
the following tree of dependencies:
```
yargs
  os-locale
    mem
```
is causing a vulnerability alert.
`mem < 4.0.0` is a subject to WS-2018-0236 vulnerability. Can you please update yargs?

The lowest version mem that's not vulnerable is 4.0.0.
The lowest version of os-locale that requires mem@^4.0.0 is 3.0.1
**The lowest version of yargs that requires os-locale@^3.0.0 is 12.0.2**

**Comment by dbhowell** [comment]
See the latest release (0.6.1), I've updated `yargs`!
